/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/dashboard/components/asrClassPlan': RouteRecordInfo<'/dashboard/components/asrClassPlan', '/dashboard/components/asrClassPlan', Record<never, never>, Record<never, never>>,
    '/dashboard/components/compareClassPlans': RouteRecordInfo<'/dashboard/components/compareClassPlans', '/dashboard/components/compareClassPlans', Record<never, never>, Record<never, never>>,
    '/dashboard/components/myClassPlans': RouteRecordInfo<'/dashboard/components/myClassPlans', '/dashboard/components/myClassPlans', Record<never, never>, Record<never, never>>,
    '/dashboard/components/newClassPlan': RouteRecordInfo<'/dashboard/components/newClassPlan', '/dashboard/components/newClassPlan', Record<never, never>, Record<never, never>>,
    '/dashboard/components/register': RouteRecordInfo<'/dashboard/components/register', '/dashboard/components/register', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
  }
}
